### ISSUE TITLE
Chrome Browser Testing

### ISSUE THREAD

**Issue by anna-trojanowska** [jazdown/portfolio#13]
This is just a style thing, but maybe the nav buttons should be more evenly spaced when the browser is full screen. Looks nice when the buttons go on either side of your name in a smaller browser size. 

The nav buttons should maybe have a current state to show the user which page they are on at the time. 

For good rhythm or flow or whatever, I would try to get the spacing between the rows of buckets the same as on the sides on the columns.  

I don't love this sentence "My portfolio is a collection of projects that I am proud to have to demonstrate my skills as a designer" maybe make it into two? 
This is just a style thing, but maybe the nav buttons should be more evenly spaced when the browser is full screen. Looks nice when the buttons go on either side of your name in a smaller browser size. 

The nav buttons should maybe have a current state to show the user which page they are on at the time. 

For good rhythm or flow or whatever, I would try to get the spacing between the rows of buckets the same as on the sides on the columns.  

I don't love this sentence "My portfolio is a collection of projects that I am proud to have to demonstrate my skills as a designer" maybe make it into two? 

In mobile size, the nav buttons sort of touch your name logo.

**Comment by jazdown** [comment]
Thank you for all the feedback
