### ISSUE TITLE
Social media on portfolio page

### ISSUE THREAD

**Issue by jazdown** [jazdown/portfolio#18]
Hey there, any idea why my social media icons on my portfolio page are in the middle of the page? It's the same code and html for my index.html and it works fine on there.
![screen shot 2015-10-09 at 9 23 53 pm](https://cloud.githubusercontent.com/assets/6373208/10408476/9b7d0b6e-6ecc-11e5-8057-4b7fe127d4f0.png)
@thomasjbradley

**Comment by thomasjbradley** [comment]
I think it has to do with the `position: absolute` on the `.social-media` class.
